FROM ubuntu:22.04

# Define o diretório de trabalho
WORKDIR /usr/local/bin

# Instala pacotes necessários
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    git \
    build-essential \
    libz-dev \
    libbz2-dev \
    liblzma-dev \
    libncurses5-dev \
    libcurl4-openssl-dev \
    wget \
    unzip \
    make \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instala as dependências Python
RUN pip install --no-cache-dir numpy scipy matplotlib biopython pysam

# Faz o download do PanDepth e instala
RUN git clone https://github.com/HuiyangYu/PanDepth.git /usr/local/PanDepth && \
    cd /usr/local/PanDepth && \
    make && \
    chmod +x bin/pandepth

# Adiciona o PanDepth ao PATH
ENV PATH="/usr/local/PanDepth:$PATH"

# Define o diretório de trabalho padrão
WORKDIR /data

# Comando de entrada padrão
ENTRYPOINT [pandepth]