FROM ubuntu:22.04

# Set the environment variables
ENV mosdepth_version 0.2.8
ENV htslib_version 1.9

# Update and install required packages
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    libnss-sss \
    curl \
    less \
    vim \
    wget \
    unzip \
    build-essential \
    libpcre3 \
    libpcre3-dev \
    zlib1g-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libbz2-dev \
    liblzma-dev \
    bzip2 \
    libcurl4-openssl-dev \
    git \
    bwa \
    cmake \
    ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install htslib
WORKDIR /usr/local/bin/
RUN curl -SL https://github.com/samtools/htslib/releases/download/${htslib_version}/htslib-${htslib_version}.tar.bz2 \
    -o htslib-${htslib_version}.tar.bz2 && \
    tar -xjf htslib-${htslib_version}.tar.bz2 && \
    rm htslib-${htslib_version}.tar.bz2 && \
    cd htslib-${htslib_version} && \
    ./configure && \
    make && \
    make install
ENV LD_LIBRARY_PATH /usr/local/bin/htslib-${htslib_version}/:$LD_LIBRARY_PATH

# Install mosdepth
RUN curl -fsSL https://github.com/brentp/mosdepth/releases/download/v${mosdepth_version}/mosdepth \
    -o /usr/bin/mosdepth && \
    chmod +x /usr/bin/mosdepth

WORKDIR /usr/local/bin/
ENTRYPOINT ["mosdepth"]