FROM ubuntu:22.04

# Para facilitar futuras atualizações de versão
ARG SAMTOOLSVER=1.21

# Instalar dependências e limpar os arquivos temporários do apt
RUN apt-get update && apt-get install --no-install-recommends -y \
    libncurses5-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-gnutls-dev \
    zlib1g-dev \
    libssl-dev \
    gcc \
    wget \
    make \
    perl \
    bzip2 \
    gnuplot \
    ca-certificates \
    gawk \
    locales && \
    apt-get autoclean && rm -rf /var/lib/apt/lists/*

# Garantir configurações locais adequadas (resolve possíveis problemas com perl e locale)
RUN locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8

# Instalar o samtools e criar o diretório /data
RUN wget https://github.com/samtools/samtools/releases/download/${SAMTOOLSVER}/samtools-${SAMTOOLSVER}.tar.bz2 && \
    tar -xjf samtools-${SAMTOOLSVER}.tar.bz2 && \
    rm samtools-${SAMTOOLSVER}.tar.bz2 && \
    cd samtools-${SAMTOOLSVER} && \
    ./configure && \
    make && \
    make install && \
    mkdir /data

# Definir configurações de locale no ambiente
ENV LC_ALL=C
ENV LANG=en_US.UTF-8

WORKDIR /data
